# version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - sn-data:/app/pkg/db
    networks:
      - sn-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GO_BACKEND_URL=http://backend:8080 # no need
      - NEXT_PUBLIC_GO_BACKEND_URL=http://localhost:8080 # ?!
      # - AUTH_SECRET=${AUTH_SECRET}
      - SKIP_ENV_VALIDATION=1
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - sn-network

volumes:
  sn-data:

networks:
  sn-network:
    driver: bridge
