FROM golang:1.24-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY backend/ .
# was after 'go mod download'

# COPY backend/go.mod ./
# backend/go.sum
RUN go mod tidy
# go mod download


RUN CGO_ENABLED=1 go build -o server .

FROM alpine:3.19

RUN apk add --no-cache ca-certificates sqlite

WORKDIR /app

COPY --from=builder /app/server .
COPY --from=builder /app/pkg/db/migrations ./pkg/db/migrations

EXPOSE 8080

CMD ["./server"]
# removed "-r" for checking volumes, and needs to add a migration for seeding!
