import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import Header from "./_components/Header";
import Sidebar from "./_components/Sidebar";
import Sidebar2 from "./_components/Sidebar2";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <main>
          <h2 className="sr-only">Social network full UI — all screens including auth, feed, profile, groups, chat, and notifications</h2>
          <div id="app">
            <Header /> {/* does it appear on login and register ?! */}
            <div className="screen active"> {/* + screen id */}
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
