CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    user_id INTEGER NOT NULL,
    actor_id INTEGER NOT NULL,

    type TEXT NOT NULL,

    object_type TEXT NOT NULL,
    object_id INTEGER NOT NULL,

    is_read INTEGER NOT NULL DEFAULT 0,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(user_id)
        REFERENCES USERS(id)
        ON DELETE CASCADE,

    FOREIGN KEY(actor_id)
        REFERENCES USERS(id)
        ON DELETE CASCADE
);

--events in groups
-- GROUP EVENTS
CREATE TABLE IF NOT EXISTS GROUP_EVENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    creator_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_time DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    FOREIGN KEY(creator_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- EVENT RESPONSES (Going / Not Going)
CREATE TABLE IF NOT EXISTS EVENT_RESPONSES (
    event_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('going', 'not_going')),
    PRIMARY KEY (event_id, user_id),
    FOREIGN KEY(event_id) REFERENCES GROUP_EVENTS(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES USERS(id) ON DELETE CASCADE
);
