DROP TABLE IF EXISTS GROUP_POST_COMMENT_REACTIONS;
DROP TABLE IF EXISTS GROUP_POST_COMMENTS;
DROP TABLE IF EXISTS GROUP_POST_REACTIONS;
DROP TABLE IF EXISTS GROUP_POSTS;
DROP TABLE IF EXISTS GROUP_REQUESTS;
DROP TABLE IF EXISTS GROUP_INVITES;
DROP TABLE IF EXISTS GROUP_MEMBERS;
DROP TABLE IF EXISTS GROUPS;
