CREATE TABLE IF NOT EXISTS GROUP_POST_COMMENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    text TEXT,

    FOREIGN KEY (group_post_id)
        REFERENCES GROUP_POSTS(id)
        ON DELETE CASCADE,
    FOREIGN KEY (user_id)
        REFERENCES USERS(id)
        ON DELETE CASCADE
);