DROP TABLE IF EXISTS COMMENT_REACTIONS;
DROP TABLE IF EXISTS POST_REACTIONS;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS POST_CATEGORY;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS POST_ALLOWED_USERS;
DROP TABLE IF EXISTS POSTS;
