--events in groups
-- GROUP EVENTS
CREATE TABLE IF NOT EXISTS GROUP_EVENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    creator_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_time DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(group_id)
        REFERENCES GROUPS(id)
        ON DELETE CASCADE,
    FOREIGN KEY(creator_id)
        REFERENCES USERS(id)
        ON DELETE CASCADE
);