CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    birthdate TEXT NOT NULL,
    nickname TEXT UNIQUE,
    aboutme TEXT,
    avatar TEXT,
    is_private INTEGER NOT NULL DEFAULT 0,
    last_seen DATETIME
);

CREATE INDEX IF NOT EXISTS idx_username ON users(nickname COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS SESSIONS (
    id TEXT PRIMARY KEY UNIQUE,
    expires_at DATETIME NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
